Add bg language
mtownsend5512/read-time pull request #14
Opened 2019-01-23 07:37 UTC by nikolalardev

2019-01-23 08:12 UTC, peter279k approved these changes

2019-01-24 04:24 UTC, mtownsend5512 commented on src/resources/lang/bg/read-time.php
> +    'min' => 'мин.',
Could you please remove the ``.`` character so it is more consistent with other translations?

2019-01-24 04:25 UTC, mtownsend5512 commented on src/resources/lang/bg/read-time.php
> +    'sec' => 'сек.',
Could you please remove the ``.`` character so it is more consistent with other translations?

2019-01-24 04:25 UTC, mtownsend5512 requested changes
Could you please remove the ``.`` character from the ``min`` and ``sec`` keys so it is more consistent with other translations?

2019-01-24 21:27 UTC, merged

2019-01-24 21:27 UTC, mtownsend5512 commented
Thanks for your contribution!